{"changes": {"content": {"new": "Hi everyone (in particular @\\_jrivero\\_ that is probably interested in this), \r\n this morning we noticed a strange behaviour when tryng to update a Gazebo 8 package in Xenial. \r\n\r\nIn particular we got this error: \r\n~~~\r\nisaac@iiticubws014:/usr/local/src/", "old": "Hi everyone (in particular @\\_jrivero\\_ that is probably interested in this), \r\n this morning we noticed a strange behaviour when tryng to update a Gazebo 8 package in Xenial. \r\n\r\nIn particular we got this error: \r\n~~~\r\nisaac@iiticubws014:/usr/local/src/"}}, "links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2268/changes/36578457.json"}, "html": {"href": "#!/osrf/gazebo/issues/2268#comment-36578457"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2268.json"}}, "type": "issue", "id": 2268, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Problems in Ubuntu Xenial Packages for Gazebo 8.1"}, "created_on": "2017-05-05T08:26:50.935436+00:00", "user": {"display_name": "Silvio Traversaro", "uuid": "{34f404cb-5642-4f27-a032-e04c7143d776}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D"}, "html": {"href": "https://bitbucket.org/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:e1c3e6a0-9a64-4e5f-a668-feebc191c5b6/578caaa1-056c-45a2-8bf9-bee94c3bebef/128"}}, "nickname": "traversaro", "type": "user", "account_id": "557058:e1c3e6a0-9a64-4e5f-a668-feebc191c5b6"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 36578457}