{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1631/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1631.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1631/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1631/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1631/errors-with-sdformat-prerelease-305"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1631/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "Errors with sdformat prerelease 3.0.5", "component": {"name": "physics", "links": {"self": {"href": "data/repositories/osrf/gazebo/components/122876.json"}}}, "votes": 0, "watches": 4, "content": {"raw": "I haven't seen any test failures (in [gazebo-default-sdformat-default](http://build.osrfoundation.org/job/gazebo-default-sdformat-default-devel-trusty-amd64/23/) for example), but the new sdformat prerelease 3.0.5 causes some error messages in gazebo when trying to load parameters of type `Vector3`:\r\n\r\n~~~\r\n[Err] [PhysicsEngine.cc:265] Caught bad any_cast in PhysicsEngine::SetParam: boost::bad_any_cast: failed conversion using boost::any_cast\r\n[Wrn] [PresetManager.cc:80] Couldn't set parameter [gravity] in physics engine\r\n[Err] [PhysicsEngine.cc:265] Caught bad any_cast in PhysicsEngine::SetParam: boost::bad_any_cast: failed conversion using boost::any_cast\r\n[Wrn] [PresetManager.cc:80] Couldn't set parameter [magnetic_field] in physics engine\r\n~~~\r\n\r\nThis didn't cause any test failures because each physics engine is apparently already reading gravity directly from sdf and not depending on the PresetManager.\r\n\r\nI added a print statement inside the `if (_value.type() == typeid(sdf::Vector3))` block in [PhysicsEngine::SetParam](#!/osrf/gazebo/src/357d75bf987b8cc53fdc4624495dc699d35a2247/gazebo/physics/PhysicsEngine.cc#cl-225), and found that it didn't enter that block. Maybe it is an `ignition::math::Vector3d` instead?", "markup": "markdown", "html": "<p>I haven't seen any test failures (in <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/gazebo-default-sdformat-default-devel-trusty-amd64/23/\" rel=\"nofollow\">gazebo-default-sdformat-default</a> for example), but the new sdformat prerelease 3.0.5 causes some error messages in gazebo when trying to load parameters of type <code>Vector3</code>:</p>\n<div class=\"codehilite\"><pre><span></span>[Err] [PhysicsEngine.cc:265] Caught bad any_cast in PhysicsEngine::SetParam: boost::bad_any_cast: failed conversion using boost::any_cast\n[Wrn] [PresetManager.cc:80] Couldn&#39;t set parameter [gravity] in physics engine\n[Err] [PhysicsEngine.cc:265] Caught bad any_cast in PhysicsEngine::SetParam: boost::bad_any_cast: failed conversion using boost::any_cast\n[Wrn] [PresetManager.cc:80] Couldn&#39;t set parameter [magnetic_field] in physics engine\n</pre></div>\n\n\n<p>This didn't cause any test failures because each physics engine is apparently already reading gravity directly from sdf and not depending on the PresetManager.</p>\n<p>I added a print statement inside the <code>if (_value.type() == typeid(sdf::Vector3))</code> block in <a data-is-external-link=\"true\" href=\"#!/osrf/gazebo/src/357d75bf987b8cc53fdc4624495dc699d35a2247/gazebo/physics/PhysicsEngine.cc#cl-225\" rel=\"nofollow\">PhysicsEngine::SetParam</a>, and found that it didn't enter that block. Maybe it is an <code>ignition::math::Vector3d</code> instead?</p>", "type": "rendered"}, "assignee": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2015-06-09T21:34:39.410221+00:00", "milestone": null, "updated_on": "2016-09-14T19:43:20.606587+00:00", "type": "issue", "id": 1631}