{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1764/comments/22493865.json"}, "html": {"href": "#!/osrf/gazebo/issues/1764#comment-22493865"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1764.json"}}, "type": "issue", "id": 1764, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "gazebo6 cannot be launched"}, "content": {"raw": "I was able to solve the problem by updating the kernel 3.19.0-31-generic.", "markup": "markdown", "html": "<p>I was able to solve the problem by updating the kernel 3.19.0-31-generic.</p>", "type": "rendered"}, "created_on": "2015-10-14T14:40:28.497656+00:00", "user": {"display_name": "Yue Hu", "uuid": "{f56515b8-7492-4cb9-aac5-f93d72e076b3}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bf56515b8-7492-4cb9-aac5-f93d72e076b3%7D"}, "html": {"href": "https://bitbucket.org/%7Bf56515b8-7492-4cb9-aac5-f93d72e076b3%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:7895fca3-fb11-4c70-9d58-7c0b0e240440/06a26000-bcae-4611-ba1d-9bd6150a9db7/128"}}, "nickname": "yue_hu", "type": "user", "account_id": "557058:7895fca3-fb11-4c70-9d58-7c0b0e240440"}, "updated_on": null, "type": "issue_comment", "id": 22493865}