{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13874854.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13874854"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2014-11-26T00:33:02.999412+00:00", "user": {"display_name": "James Taylor", "uuid": "{80a5efd1-140d-4624-a75d-d114628c1db8}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D"}, "html": {"href": "https://bitbucket.org/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3cbda94bb60d047f7d10c50d7d847d5ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJT-3.png"}}, "nickname": "jrtaylor", "type": "user", "account_id": "557058:e8ac7e8b-59fe-4119-a528-7d0f5b851e6e"}, "updated_on": null, "type": "issue_comment", "id": 13874854}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13875365.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13875365"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "One addendum that may be related to the model failure and not necessarily the other distro issues.  Today, I received notice that Nate approved the ur10 model.  The model I was working was my version of the ur10.  I was using my model path preceding the gazebo model path, so I assume that it was trying to parse my local model.  However, it could be related if the gazebo_models ur10 was rolled out today; although, it did not appear in the available download list visible in gazebo so I discounted that as the issue in the earlier summary.  ", "markup": "markdown", "html": "<p>One addendum that may be related to the model failure and not necessarily the other distro issues.  Today, I received notice that Nate approved the ur10 model.  The model I was working was my version of the ur10.  I was using my model path preceding the gazebo model path, so I assume that it was trying to parse my local model.  However, it could be related if the gazebo_models ur10 was rolled out today; although, it did not appear in the available download list visible in gazebo so I discounted that as the issue in the earlier summary.  </p>", "type": "rendered"}, "created_on": "2014-11-26T01:22:23.682437+00:00", "user": {"display_name": "James Taylor", "uuid": "{80a5efd1-140d-4624-a75d-d114628c1db8}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D"}, "html": {"href": "https://bitbucket.org/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3cbda94bb60d047f7d10c50d7d847d5ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJT-3.png"}}, "nickname": "jrtaylor", "type": "user", "account_id": "557058:e8ac7e8b-59fe-4119-a528-7d0f5b851e6e"}, "updated_on": null, "type": "issue_comment", "id": 13875365}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13875675.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13875675"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "Hi @jrtaylor\n\nHow can I reproduce the same failure you are seeing?  Can you share the model file that fails to parse?  Also, please post any failure messages if any (try `gazebo --verbose` to get more output).\n\n@hsu", "markup": "markdown", "html": "<p>Hi @jrtaylor</p>\n<p>How can I reproduce the same failure you are seeing?  Can you share the model file that fails to parse?  Also, please post any failure messages if any (try <code>gazebo --verbose</code> to get more output).</p>\n<p>@hsu</p>", "type": "rendered"}, "created_on": "2014-11-26T01:56:14.504562+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "updated_on": null, "type": "issue_comment", "id": 13875675}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13875682.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13875682"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2014-11-26T01:56:54.066356+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "updated_on": null, "type": "issue_comment", "id": 13875682}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13875689.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13875689"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "Also, can you list out your current system state before wiping the system?  For example:\n\n~~~\nsdformat from sdf_2.0 branch tip\ngazebo from gazebo_4.1 branch tip\ndart-core4.2 from debian\n... etc ...\n~~~", "markup": "markdown", "html": "<p>Also, can you list out your current system state before wiping the system?  For example:</p>\n<div class=\"codehilite\"><pre><span></span>sdformat from sdf_2.0 branch tip\ngazebo from gazebo_4.1 branch tip\ndart-core4.2 from debian\n... etc ...\n</pre></div>", "type": "rendered"}, "created_on": "2014-11-26T01:57:54.224664+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "updated_on": "2014-11-26T01:58:25.178398+00:00", "type": "issue_comment", "id": 13875689}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13875860.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13875860"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "John, unfortunately in order to recreate the issue on your end as it stands now, you would have to meet reveal requirements as the controllers and the validation code have that dependency.  I am going to try to pare down the example tomorrow and run it on my other system, so if that fails, I will attach the pared down package to this thread.\n\nI grab all the info I can tomorrow before I take any action and post here.  If there is anything else you need, let me know.", "markup": "markdown", "html": "<p>John, unfortunately in order to recreate the issue on your end as it stands now, you would have to meet reveal requirements as the controllers and the validation code have that dependency.  I am going to try to pare down the example tomorrow and run it on my other system, so if that fails, I will attach the pared down package to this thread.</p>\n<p>I grab all the info I can tomorrow before I take any action and post here.  If there is anything else you need, let me know.</p>", "type": "rendered"}, "created_on": "2014-11-26T02:16:13.637091+00:00", "user": {"display_name": "James Taylor", "uuid": "{80a5efd1-140d-4624-a75d-d114628c1db8}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D"}, "html": {"href": "https://bitbucket.org/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3cbda94bb60d047f7d10c50d7d847d5ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJT-3.png"}}, "nickname": "jrtaylor", "type": "user", "account_id": "557058:e8ac7e8b-59fe-4119-a528-7d0f5b851e6e"}, "updated_on": null, "type": "issue_comment", "id": 13875860}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13876037.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13876037"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "I just compiled gazebo_4.1 branch against dart v4.2.0 locally, no obvious failures there.\n\nLet me know if you are able to create a simple test that demonstrates this failure. Thanks.", "markup": "markdown", "html": "<p>I just compiled gazebo_4.1 branch against dart v4.2.0 locally, no obvious failures there.</p>\n<p>Let me know if you are able to create a simple test that demonstrates this failure. Thanks.</p>", "type": "rendered"}, "created_on": "2014-11-26T02:31:07.138710+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "updated_on": "2014-11-26T02:31:19.803479+00:00", "type": "issue_comment", "id": 13876037}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13895502.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13895502"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": "Installed Reveal requirements on secondary machine and was able to run the project.  This issues appears to be an environmental change on this system, but what could have caused it eludes me as nothing was explicitly applied between the working attempt and the non-working attempt.  I am going to purge gazebo on this machine and reset.  Below is the environment as it was before everything went sour.\n\n```\n#!c++\ngazebo from gazebo_4.0 branch tip\nsdformat from sdf_2.0 branch tip\n```\nfollowing http://gazebosim.org/tutorials?tut=install for optional physics on Precise\n```\n#!c++\ndart_core4.1 from debian\nbullet 2.82 from debian\nsimbody 3.3 from debian\n```\n\nThe exceptions generated were\n```\n#!c++\n[Err] [Exception.cc:52] EXCEPTION: Couldn't Find Child Link[ur10::base_link]\n\n[Err] [Model.cc:138] LoadJoint Failed\n[Err] [Exception.cc:52] EXCEPTION: Couldn't Find Parent Link[ur10::wrist_3_link]\n\n[Err] [Model.cc:138] LoadJoint Failed\n```\nThe links do exist in the models and it was somehow related to nesting models.  But just to reiterate, this model was working moments before the anomaly and it does continue to work on another machine.  The joints in question are fixed joints that weld the base_link to the world and the wrist_3_link to the gripper.", "markup": "markdown", "html": "<p>Installed Reveal requirements on secondary machine and was able to run the project.  This issues appears to be an environmental change on this system, but what could have caused it eludes me as nothing was explicitly applied between the working attempt and the non-working attempt.  I am going to purge gazebo on this machine and reset.  Below is the environment as it was before everything went sour.</p>\n<div class=\"codehilite language-c++\"><pre><span></span><span class=\"n\">gazebo</span> <span class=\"n\">from</span> <span class=\"n\">gazebo_4</span><span class=\"mf\">.0</span> <span class=\"n\">branch</span> <span class=\"n\">tip</span>\n<span class=\"n\">sdformat</span> <span class=\"n\">from</span> <span class=\"n\">sdf_2</span><span class=\"mf\">.0</span> <span class=\"n\">branch</span> <span class=\"n\">tip</span>\n</pre></div>\n\n\n<p>following <a href=\"http://gazebosim.org/tutorials?tut=install\" rel=\"nofollow\" class=\"ap-connect-link\">http://gazebosim.org/tutorials?tut=install</a> for optional physics on Precise</p>\n<div class=\"codehilite language-c++\"><pre><span></span><span class=\"n\">dart_core4</span><span class=\"mf\">.1</span> <span class=\"n\">from</span> <span class=\"n\">debian</span>\n<span class=\"n\">bullet</span> <span class=\"mf\">2.82</span> <span class=\"n\">from</span> <span class=\"n\">debian</span>\n<span class=\"n\">simbody</span> <span class=\"mf\">3.3</span> <span class=\"n\">from</span> <span class=\"n\">debian</span>\n</pre></div>\n\n\n<p>The exceptions generated were</p>\n<div class=\"codehilite language-c++\"><pre><span></span><span class=\"p\">[</span><span class=\"n\">Err</span><span class=\"p\">]</span> <span class=\"p\">[</span><span class=\"n\">Exception</span><span class=\"p\">.</span><span class=\"nl\">cc</span><span class=\"p\">:</span><span class=\"mi\">52</span><span class=\"p\">]</span> <span class=\"nl\">EXCEPTION</span><span class=\"p\">:</span> <span class=\"n\">Couldn</span><span class=\"err\">&#39;</span><span class=\"n\">t</span> <span class=\"n\">Find</span> <span class=\"n\">Child</span> <span class=\"n\">Link</span><span class=\"p\">[</span><span class=\"n\">ur10</span><span class=\"o\">::</span><span class=\"n\">base_link</span><span class=\"p\">]</span>\n\n<span class=\"p\">[</span><span class=\"n\">Err</span><span class=\"p\">]</span> <span class=\"p\">[</span><span class=\"n\">Model</span><span class=\"p\">.</span><span class=\"nl\">cc</span><span class=\"p\">:</span><span class=\"mi\">138</span><span class=\"p\">]</span> <span class=\"n\">LoadJoint</span> <span class=\"n\">Failed</span>\n<span class=\"p\">[</span><span class=\"n\">Err</span><span class=\"p\">]</span> <span class=\"p\">[</span><span class=\"n\">Exception</span><span class=\"p\">.</span><span class=\"nl\">cc</span><span class=\"p\">:</span><span class=\"mi\">52</span><span class=\"p\">]</span> <span class=\"nl\">EXCEPTION</span><span class=\"p\">:</span> <span class=\"n\">Couldn</span><span class=\"err\">&#39;</span><span class=\"n\">t</span> <span class=\"n\">Find</span> <span class=\"n\">Parent</span> <span class=\"n\">Link</span><span class=\"p\">[</span><span class=\"n\">ur10</span><span class=\"o\">::</span><span class=\"n\">wrist_3_link</span><span class=\"p\">]</span>\n\n<span class=\"p\">[</span><span class=\"n\">Err</span><span class=\"p\">]</span> <span class=\"p\">[</span><span class=\"n\">Model</span><span class=\"p\">.</span><span class=\"nl\">cc</span><span class=\"p\">:</span><span class=\"mi\">138</span><span class=\"p\">]</span> <span class=\"n\">LoadJoint</span> <span class=\"n\">Failed</span>\n</pre></div>\n\n\n<p>The links do exist in the models and it was somehow related to nesting models.  But just to reiterate, this model was working moments before the anomaly and it does continue to work on another machine.  The joints in question are fixed joints that weld the base_link to the world and the wrist_3_link to the gripper.</p>", "type": "rendered"}, "created_on": "2014-11-26T19:36:08.350317+00:00", "user": {"display_name": "James Taylor", "uuid": "{80a5efd1-140d-4624-a75d-d114628c1db8}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D"}, "html": {"href": "https://bitbucket.org/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3cbda94bb60d047f7d10c50d7d847d5ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJT-3.png"}}, "nickname": "jrtaylor", "type": "user", "account_id": "557058:e8ac7e8b-59fe-4119-a528-7d0f5b851e6e"}, "updated_on": "2014-11-26T20:35:33.521530+00:00", "type": "issue_comment", "id": 13895502}, {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/30610219.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-30610219"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2016-09-14T19:22:04.208213+00:00", "user": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}, "updated_on": null, "type": "issue_comment", "id": 30610219}], "page": 1, "size": 9}