{"links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/2639/comments/31469925.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/diff/osrf/gazebo:bb7d454be993..da848d7663a1?path=gazebo%2Fgui%2FDataLogger_TEST.cc"}, "html": {"href": "#!/osrf/gazebo/pull-requests/2639/_/diff#comment-31469925"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 2639, "links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/2639.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/2639"}}, "title": "Fix memory leaks in tests"}, "content": {"raw": "\"[failure is recorded in the test log and the test won't be executed further](http://doc.qt.io/qt-5/qtest.html#QVERIFY)\". I think that means QVERIFY raises an exception on failure. Maybe make dataLogger a scoped pointer instead?", "markup": "markdown", "html": "<p>\"<a data-is-external-link=\"true\" href=\"http://doc.qt.io/qt-5/qtest.html#QVERIFY\" rel=\"nofollow\">failure is recorded in the test log and the test won't be executed further</a>\". I think that means QVERIFY raises an exception on failure. Maybe make dataLogger a scoped pointer instead?</p>", "type": "rendered"}, "created_on": "2017-02-14T17:46:38.923183+00:00", "user": {"display_name": "Shane Loretz", "uuid": "{656e3311-aad9-45a1-aaf7-b0ee0e84b287}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D"}, "html": {"href": "https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:684383ab-ac95-4859-a350-4a6f41a94a22/c7a1ebf5-cade-4115-9f26-9d3facb776db/128"}}, "nickname": "Shane Loretz", "type": "user", "account_id": "557058:684383ab-ac95-4859-a350-4a6f41a94a22"}, "inline": {"to": null, "from": 203, "outdated": true, "path": "gazebo/gui/DataLogger_TEST.cc"}, "updated_on": "2017-02-14T17:46:38.926957+00:00", "type": "pullrequest_comment", "id": 31469925}